name: regular-push
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
          java-package: jdk

      - name: Install sfdx
        run: npm install sfdx-cli

      - name: Install Scanner
        run: node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner

      - name: Scan base
        run: node_modules/sfdx-cli/bin/run scanner:run --target ".\**\*" --violations-cause-error
